apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coder-clusterapi-perms
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "list"
      - "get"
  - apiGroups:
      - ""
      - "cluster.x-k8s.io"
      - "bootstrap.cluster.x-k8s.io"
      - "controlplane.cluster.x-k8s.io"
      - "infrastructure.cluster.x-k8s.io"
      - "addons.cluster.x-k8s.io"
      - "cdi.kubevirt.io"
    resources:
      - "namespaces"
      - "configmaps"
      - "clusters"
      - "machinedeployments"
      - "talosconfigtemplates"
      - "taloscontrolplanes"
      - "kubevirtclusters"
      - "kubevirtmachinetemplates"
      - "clusterresourcesets"
      - "kubeadmconfigtemplates"
      - "kubeadmcontrolplanes"
      - "datavolumes"
    verbs:
      - "list"
      - "get"
      - "patch"
      - "create"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-clusterapi
  namespace: coder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coder-clusterapi-perms
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: coder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-clusterapi-cluster
  namespace: coder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coder-clusterapi-perms
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: coder
